datasource:
  bpm:
    url: jdbc:h2:mem:bpm
    driver-class-name: org.h2.Driver
  model:
    url: jdbc:h2:mem:app
    driver-class-name: org.h2.Driver

camunda.bpm:
  admin-user:
    id: admin
    password: admin
    firstName: Alice
    lastName: Bob
  filter:
    create: All tasks

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:app
  h2:
    console:
      enable: true
      path: /h2-console